apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e2mh2t737-nodejs 
  janus-idp.io/tekton: e2mh2t737-nodejs
  backstage.io/kubernetes-id: e2mh2t737-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e2mh2t737-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  