apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e2mh2t737-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2mh2t737-nodejs 
  name: e2mh2t737-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e2mh2t737-nodejs 
